/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/drawer/Drawer.vue')['default']
    DrawerSettings: typeof import('./src/components/drawer/Drawer-settings.vue')['default']
    DrawerTimer: typeof import('./src/components/drawer/Drawer-timer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Notification: typeof import('./src/components/notification/Notification.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
    TaskList: typeof import('./src/components/task/TaskList.vue')['default']
    Timer: typeof import('./src/components/timer/Timer.vue')['default']
    TimerAudio: typeof import('./src/components/TimerAudio.vue')['default']
    TimerController: typeof import('./src/components/timer/Timer-controller.vue')['default']
    TimerDial: typeof import('./src/components/timer/Timer-dial.vue')['default']
    TimerFooter: typeof import('./src/components/timer/Timer-footer.vue')['default']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
  }
}
