version: '1.0'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PORT: 8083
    ports:
      - 8083:8083

volumes:
  db:
    driver: local